### ISSUE TITLE
How to release Jar 

### ISSUE THREAD

**Issue by Elqul** [dialogs/sbt-dialog-api#1]
hello,

how do you release sbt-dialog-api jar with SBT ?

**Comment by prettynatty** [comment]
Hey @Elqul ,
we just execute `sbt publish` and build is heading to our bintray repo.
But I suggest you to take a look at our [commons](https://github.com/dialogs/commons) project which is using `sbt-release` in conjunction with `sbt-bintray` for jar releasing.
